In [13]:
from tensorflow.keras.preprocessing.text import one_hot


In [14]:
#sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [15]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
#define the vocab size
voc_size = 10000

In [17]:
one_hot_repr=[one_hot(words , voc_size)for words in sent]
one_hot_repr

[[1792, 5461, 1868, 1271],
 [1792, 5461, 1868, 2862],
 [1792, 3446, 1868, 5783],
 [5236, 3731, 2173, 1126, 4937],
 [5236, 3731, 2173, 1126, 2387],
 [9567, 1792, 1576, 1868, 9334],
 [7184, 9750, 289, 1126]]

In [18]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
sent_length = 8
embedded_seq= pad_sequences(one_hot_repr , padding ='post', maxlen=sent_length)
print(embedded_seq)

[[1792 5461 1868 1271    0    0    0    0]
 [1792 5461 1868 2862    0    0    0    0]
 [1792 3446 1868 5783    0    0    0    0]
 [5236 3731 2173 1126 4937    0    0    0]
 [5236 3731 2173 1126 2387    0    0    0]
 [9567 1792 1576 1868 9334    0    0    0]
 [7184 9750  289 1126    0    0    0    0]]


In [20]:
#feature representtaion
dim = 10

In [21]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential()
model.add(Input(shape=(sent_length,)))   # Explicit Input Layer
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.compile(optimizer='adam', loss='mse')
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step


array([[[ 0.02730029,  0.00778781, -0.00862913, -0.02152966,
          0.02267499,  0.00128522, -0.03897827, -0.00849404,
          0.02262789,  0.02060017],
        [-0.01657466,  0.00721356,  0.02707139,  0.03690923,
          0.02398146,  0.04613281,  0.01902283, -0.0461162 ,
          0.04398929,  0.03252156],
        [-0.03234948, -0.04380881,  0.04606495,  0.04566364,
          0.01093674, -0.00334848,  0.0333111 , -0.04539835,
         -0.03386962, -0.04883114],
        [-0.0041277 ,  0.01984929,  0.01381813, -0.04700169,
          0.02417529, -0.01829847,  0.04675312,  0.03471929,
         -0.03411599,  0.02375336],
        [ 0.04641333,  0.03213121,  0.03046825,  0.01190054,
          0.03669889, -0.03343154,  0.0445771 ,  0.02684304,
         -0.03455655,  0.01844329],
        [ 0.04641333,  0.03213121,  0.03046825,  0.01190054,
          0.03669889, -0.03343154,  0.0445771 ,  0.02684304,
         -0.03455655,  0.01844329],
        [ 0.04641333,  0.03213121,  0.03046825,  0.0

In [23]:
embedded_seq[0]

array([1792, 5461, 1868, 1271,    0,    0,    0,    0], dtype=int32)

In [24]:
model.predict(embedded_seq[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[[ 0.02730029,  0.00778781, -0.00862913, -0.02152966,
          0.02267499,  0.00128522, -0.03897827, -0.00849404,
          0.02262789,  0.02060017],
        [-0.01657466,  0.00721356,  0.02707139,  0.03690923,
          0.02398146,  0.04613281,  0.01902283, -0.0461162 ,
          0.04398929,  0.03252156],
        [-0.03234948, -0.04380881,  0.04606495,  0.04566364,
          0.01093674, -0.00334848,  0.0333111 , -0.04539835,
         -0.03386962, -0.04883114],
        [-0.0041277 ,  0.01984929,  0.01381813, -0.04700169,
          0.02417529, -0.01829847,  0.04675312,  0.03471929,
         -0.03411599,  0.02375336],
        [ 0.04641333,  0.03213121,  0.03046825,  0.01190054,
          0.03669889, -0.03343154,  0.0445771 ,  0.02684304,
         -0.03455655,  0.01844329],
        [ 0.04641333,  0.03213121,  0.03046825,  0.01190054,
          0.03669889, -0.03343154,  0.0445771 ,  0.02684304,
         -0.03455655,  0.01844329],
        [ 0.04641333,  0.03213121,  0.03046825,  0.0